apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
   name: kubia
spec:
   replicas: 2
   selector:  
     matchLabels:
      app: kubia2
   template:
      metadata:
        labels:
          app: kubia2
      spec:
        containers:
        - name: kubia3
          image: luksa/kubia
          ports:
          - name: http
            containerPort: 8080
