apiVersion: v1
kind: PersistentVolume
metadata:
   name: mongodb-pv
spec:
    capacity:
       storage: 1Gi  
    accessModes:      
    - ReadWriteOnce
    - ReadOnlyMany
    persistentVolumeReclaimPolicy: Retain  
    nfs:
      server: 10.211.55.15
      path: /nfs-data/mongodb
