apiVersion: v1
kind: Pod
metadata:
   name: pod-drop-chown-capalibity
spec:
   containers:
   - name: main
     image: alpine
     command: ["/bin/sleep","99999"]
     securityContext:
        capabilities:
          drop:
          - CHOWN
