apiVersion: v1
kind: Pod
metadata:
   name: pod-run-as-non-root
spec:
   containers:
   - name: main
     image: alpine
     command: ["sleep","99999"]
     securityContext:
       runAsNonRoot: true
