apiVersion: extensions/v1beta1
kind: Deployment
metadata:
   name: prod
spec:
   replicas: 10
   template:
     metadata:
        name: kubia-test
        labels:
           app: kubia-deployment-test
     spec:
       containers:
       - image: busybox
         command: ["sleep","999999"]
         name: test
       affinity:
         nodeAffinity:
           preferredDuringSchedulingIgnoredDuringExecution:
           - weight: 80
             preference:
                 matchExpressions:
                 - key: availability-zone
                   operator: In
                   values:
                   - zone1
           - weight: 20
             preference:
                 matchExpressions:
                 - key: share-type
                   operator: In
                   values:
                   - dedicated 
