apiVersion: v1
kind: Pod
metadata:
   name: fortune-configmap-volume
spec:
  containers:
  - image: nginx:alpine
    name: web-server
    volumeMounts:
    - name: config
      mountPath: /etc/nginx/conf.d
      readOnly: true
    ports:
    - containerPort: 80
      protocol: TCP
  volumes:
  - name: config
    configMap:
      name: fortune-nginx
      items:
      - key: my-nginx-config.conf 
        path: gzip.conf 
