apiVersion: v1
kind: ReplicationController
metadata:
  name: kubia-1
spec:
  replicas: 3
  template:
     metadata: 
       name: kubia
       labels:
         app: kubia-v1
     spec:
       containers:
       - image: luksa/kubia:v1
         name: nodejs
---
apiVersion: v1
kind: Service
metadata:
   name: kubia-v1-service
spec:
  type: NodePort
  selector:
     app: kubia-v1
  ports:
  - port: 8888
    targetPort: 8080 
