apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kubia-deployment
spec:
  replicas: 2
  template:
     metadata: 
       name: kubia
       labels:
         app: kubia-deployment
     spec:
       containers:
       - image: luksa/kubia:v1
         name: nodejs
---
apiVersion: v1
kind: Service
metadata:
   name: kubia-deployment-service
spec:
  type: NodePort
  selector:
     app: kubia-deployment
  ports:
  - port: 8888
    targetPort: 8080 
