apiVersion: v1
kind: ReplicationController
metadata:
   name: rc-nginx
spec:
   replicas: 3
   selector: 
      app: rc-nginx
   template:
      metadata:
        labels:
          app: rc-nginx
      spec:
        containers:
        - name: rc-nginx
          image: nginx:latest
          ports:
          - containerPort: 80
