apiVersion: v1
kind: Service
metadata:
  labels:
    run: nginx
  name: nginx
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 88
    targetPort: 80
    nodePort: 30002
  selector:
    app: nginx

