apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
   name: rcs-nginx
spec:
   replicas: 2
   selector:
      matchLabels:
        app: rc-nginx,rc-nginx2
   template:
      metadata:
         labels:
            app: rc-nginx
   spec:
      containers:
      -name: rc-nginx
      image: nginx:latest
