apiVersion: v1
data:
  sleep-interval: "25"
kind: ConfigMap
metadata:
  creationTimestamp: "2019-06-12T04:54:06Z"
  name: fortune-config
  namespace: default
  resourceVersion: "320862"
  selfLink: /api/v1/namespaces/default/configmaps/fortune-config
  uid: 1b6e15cd-8cce-11e9-8483-001c4284a633
