apiVersion: v1
kind: Pod
metadata:
  name: fortune-env
spec:
  containers:
    - image: calvindai/fortune:env
      env:
      - name: INTERVAL
        valueFrom:
          configMapKeyRef:
              name: fortune-config
              key: sleep-interval
      name: html-generator
  nodeSelector:
     node: work-1
