apiVersion: v1
kind: Pod
metadata:
  name: fortune-env
spec:
  containers:
    - image: calvindai/fortune:env
      env:
      - name: INTERVAL2
        value: "30"
      - name: INTERVAL
        value: $(INTERVAL2)
      name: html-generator
  nodeSelector:
     node: work-1
